### ISSUE TITLE
`set-output` is deprecated

### ISSUE THREAD

**Issue by mikestopcontinues** [SamhammerAG/last-successful-build-action#5]
I'm getting the following warning:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I suspect the `@github/actions` package needs to be updated, since it seems `set-output` is being used under the hood.

**Comment by domi2120** [comment]
@mikestopcontinues I'm not seeing this warning on any of my workflows using this action. The @actions/core package is currently on version 1.10.0 which should already contain a fix according to this [comment](https://github.com/actions/toolkit/issues/1218#issuecomment-1554608943) and the [release notes](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md#1100).  Are you using the newest version of this action and sure that the warning is caused by it ?

**Comment by mikestopcontinues** [comment]
I'm as confident as I can be. If I disable just the plugin, the warning disappears. (I just tried again.)

Is it possible one of the conditions in the comment aren't being met? In particular, does `$GITHUB_OUTPUT` need to be set manually in addition to `core.setOutput()`? 

Here's the error:

<img width="927" alt="Screenshot 2023-06-16 at 9 16 38 AM" src="https://github.com/SamhammerAG/last-successful-build-action/assets/150434/1dcf9bf1-c5fa-4f18-b10e-b7488e6378bc">

Here's my config:

```yaml
      - name: Lookup Last Success
        id: last-success
        uses: SamhammerAG/last-successful-build-action@v2
        with:
          branch: ${{github.ref_name}}
          workflow: ${{github.workflow}}
          token: ${{github.token}}
          verify: false
```
