### ISSUE TITLE
Get Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by zhaoyi0113** [SamhammerAG/last-successful-build-action#8]
I have configured workflow as below but I get this error from github action when running this job:

```
Run SamhammerAG/last-successful-build-action@v4
  with:
    branch: develop
    workflow: main
    token: ***
    verify: false
Error: Resource not accessible by integration
```

What does `Error: Resource not accessible by integration` mean? Does this plugin require any permissions?

```
jobs:
  last-success-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: SamhammerAG/last-successful-build-action@v4
        id: last-successful-commit
        with:
          branch: 'develop'
          workflow: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by domi2120** [comment]
@zhaoyi0113 The screenshot shows the permission configuration for the GITHUB_TOKEN (example `${{ github.token }}` ). In your example you're using `${{ secrets.GITHUB_TOKEN }}` which refers to a custom secret in your repository. Can you check the permissions given to the token contained in that secret ? (Instead you could also leave out the token parameter so the action will use the default value of `${{ github.token }}`

**Comment by gmitche1** [comment]
It seems that this action requires permissions for actions: read, which does not seem be a default permission granted under Workflow permissions of "Read repository and package permissions" setting. This action works by setting the permissions on the job, for example

```
jobs:
  show-last-success:
    runs-on: [ ubuntu-latest ]
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Find successful workflow by name
        uses: SamhammerAG/last-successful-build-action@v5
        with:
          branch: "main"
          workflow: "Some other deploy"
      - name: Show result
        run: |
          echo Last successful deploy SHA: ${{ github.sha }}
```
